import { createRouter, createWebHistory } from 'vue-router';
import AdminLayout from '@/layouts/AdminLayout.vue';
import AuthenticationLayout from '@/layouts/AuthenticationLayout.vue';
import { useAuthStore } from '@/modules/authentication/stores/auth';

const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: '/auth',
      component: AuthenticationLayout,
      meta: { guest: true },
      children: [
        {
          path: 'login',
          name: 'login',
          component: () => import('@/modules/authentication/pages/LoginPage.vue'),
          meta: { title: 'Login', guest: true },
        },
        {
          path: 'forgot-password',
          name: 'forgot-password',
          component: () => import('@/modules/authentication/pages/ForgotPasswordPage.vue'),
          meta: { title: 'Forgot Password', guest: true },
        },
        {
          path: 'reset-password',
          name: 'reset-password',
          component: () => import('@/modules/authentication/pages/ResetPasswordPage.vue'),
          meta: { title: 'Reset Password', guest: true },
        },
        {
          path: 'verify-email',
          name: 'verify-email',
          component: () => import('@/modules/authentication/pages/EmailVerificationPage.vue'),
          meta: { title: 'Verify Email', guest: true },
        },
      ],
    },
    {
      path: '/',
      component: AdminLayout,
      meta: { requiresAuth: true },
      children: [
        {
          path: '',
          name: 'dashboard',
          component: () => import('@/pages/DashboardPage.vue'),
          meta: { title: 'Dashboard', requiresAuth: true },
        },
        {
          path: 'users',
          name: 'users.index',
          component: () => import('@/modules/users/pages/UsersListPage.vue'),
          meta: { title: 'Users', requiresAuth: true },
        },
        {
          path: 'users/create',
          name: 'users.create',
          component: () => import('@/modules/users/pages/CreateUserPage.vue'),
          meta: { title: 'Create User', requiresAuth: true },
        },
        {
          path: 'users/:id',
          name: 'users.show',
          component: () => import('@/modules/users/pages/ViewUserPage.vue'),
          meta: { title: 'User Details', requiresAuth: true },
        },
        {
          path: 'users/:id/edit',
          name: 'users.edit',
          component: () => import('@/modules/users/pages/EditUserPage.vue'),
          meta: { title: 'Edit User', requiresAuth: true },
        },
        {
          path: 'roles',
          name: 'roles.index',
          component: () => import('@/modules/roles/pages/RolesListPage.vue'),
          meta: { title: 'Roles', requiresAuth: true },
        },
        {
          path: 'roles/create',
          name: 'roles.create',
          component: () => import('@/modules/roles/pages/CreateRolePage.vue'),
          meta: { title: 'Create Role', requiresAuth: true },
        },
        {
          path: 'roles/matrix',
          name: 'roles.matrix',
          component: () => import('@/modules/roles/pages/PermissionMatrixPage.vue'),
          meta: { title: 'Permission Matrix', requiresAuth: true },
        },
        {
          path: 'roles/assign',
          name: 'roles.assign',
          component: () => import('@/modules/roles/pages/AssignRolesPage.vue'),
          meta: { title: 'Assign Roles', requiresAuth: true },
        },
        {
          path: 'roles/:id',
          name: 'roles.show',
          component: () => import('@/modules/roles/pages/ViewRolePage.vue'),
          meta: { title: 'Role Details', requiresAuth: true },
        },
        {
          path: 'roles/:id/edit',
          name: 'roles.edit',
          component: () => import('@/modules/roles/pages/EditRolePage.vue'),
          meta: { title: 'Edit Role', requiresAuth: true },
        },
        {
          path: 'roles/:id/permissions',
          name: 'roles.permissions',
          component: () => import('@/modules/roles/pages/AssignPermissionsPage.vue'),
          meta: { title: 'Assign Permissions', requiresAuth: true },
        },
        {
          path: 'companies',
          name: 'companies.index',
          component: () => import('@/modules/companies/pages/CompaniesListPage.vue'),
          meta: { title: 'Companies', requiresAuth: true },
        },
        {
          path: 'companies/create',
          name: 'companies.create',
          component: () => import('@/modules/companies/pages/CreateCompanyPage.vue'),
          meta: { title: 'Create Company', requiresAuth: true },
        },
        {
          path: 'companies/:id',
          name: 'companies.show',
          component: () => import('@/modules/companies/pages/ViewCompanyPage.vue'),
          meta: { title: 'Company Details', requiresAuth: true },
        },
        {
          path: 'companies/:id/edit',
          name: 'companies.edit',
          component: () => import('@/modules/companies/pages/EditCompanyPage.vue'),
          meta: { title: 'Edit Company', requiresAuth: true },
        },
        {
          path: 'companies/:id/profile',
          name: 'companies.profile',
          component: () => import('@/modules/companies/pages/CompanyProfilePage.vue'),
          meta: { title: 'Company Profile', requiresAuth: true },
        },
        {
          path: 'companies/:id/departments',
          name: 'companies.departments',
          component: () => import('@/modules/companies/pages/DepartmentsPage.vue'),
          meta: { title: 'Departments', requiresAuth: true },
        },
        {
          path: 'companies/:id/teams',
          name: 'companies.teams',
          component: () => import('@/modules/companies/pages/TeamsPage.vue'),
          meta: { title: 'Teams', requiresAuth: true },
        },
        {
          path: 'companies/:id/locations',
          name: 'companies.locations',
          component: () => import('@/modules/companies/pages/LocationsPage.vue'),
          meta: { title: 'Locations', requiresAuth: true },
        },
        {
          path: 'applications',
          name: 'applications.index',
          component: () => import('@/modules/applications/pages/ApplicationsListPage.vue'),
          meta: { title: 'Applications', requiresAuth: true },
        },
        {
          path: 'applications/create',
          name: 'applications.create',
          component: () => import('@/modules/applications/pages/CreateApplicationPage.vue'),
          meta: { title: 'Create Application', requiresAuth: true },
        },
        {
          path: 'applications/:id',
          name: 'applications.show',
          component: () => import('@/modules/applications/pages/ViewApplicationPage.vue'),
          meta: { title: 'Application Details', requiresAuth: true },
        },
        {
          path: 'applications/:id/edit',
          name: 'applications.edit',
          component: () => import('@/modules/applications/pages/EditApplicationPage.vue'),
          meta: { title: 'Edit Application', requiresAuth: true },
        },
        {
          path: 'content',
          name: 'content.dashboard',
          component: () => import('@/modules/content/pages/ContentDashboardPage.vue'),
          meta: { title: 'Content Dashboard', requiresAuth: true },
        },
        {
          path: 'content/list',
          name: 'content.index',
          component: () => import('@/modules/content/pages/ContentListPage.vue'),
          meta: { title: 'Content', requiresAuth: true },
        },
        {
          path: 'content/create',
          name: 'content.create',
          component: () => import('@/modules/content/pages/CreateContentPage.vue'),
          meta: { title: 'Create Content', requiresAuth: true },
        },
        {
          path: 'content/categories',
          name: 'content.categories',
          component: () => import('@/modules/content/pages/CategoryListPage.vue'),
          meta: { title: 'Categories', requiresAuth: true },
        },
        {
          path: 'content/tags',
          name: 'content.tags',
          component: () => import('@/modules/content/pages/TagManagerPage.vue'),
          meta: { title: 'Tag Manager', requiresAuth: true },
        },
        {
          path: 'content/media',
          name: 'content.media',
          component: () => import('@/modules/content/pages/MediaManagerPage.vue'),
          meta: { title: 'Media Library', requiresAuth: true },
        },
        {
          path: 'content/workflow',
          name: 'content.workflow',
          component: () => import('@/modules/content/pages/ApprovalQueuePage.vue'),
          meta: { title: 'Approval Queue', requiresAuth: true },
        },
        {
          path: 'content/delivery',
          name: 'content.delivery',
          component: () => import('@/modules/content/pages/CmsDeliveryPreviewPage.vue'),
          meta: { title: 'CMS Delivery Preview', requiresAuth: true },
        },
        {
          path: 'content/seo',
          name: 'content.seo',
          component: () => import('@/modules/content/pages/CmsSeoToolsPage.vue'),
          meta: { title: 'SEO Tools', requiresAuth: true },
        },
        {
          path: 'content/api-explorer',
          name: 'content.api-explorer',
          component: () => import('@/modules/content/pages/HeadlessApiExplorerPage.vue'),
          meta: { title: 'CMS API Explorer', requiresAuth: true },
        },
        {
          path: 'content/:id',
          name: 'content.show',
          component: () => import('@/modules/content/pages/ViewContentPage.vue'),
          meta: { title: 'Content Details', requiresAuth: true },
        },
        {
          path: 'content/:id/edit',
          name: 'content.edit',
          component: () => import('@/modules/content/pages/EditContentPage.vue'),
          meta: { title: 'Edit Content', requiresAuth: true },
        },
        {
          path: 'content/:id/review',
          name: 'content.review',
          component: () => import('@/modules/content/pages/ContentReviewPage.vue'),
          meta: { title: 'Content Review', requiresAuth: true },
        },
        {
          path: 'content/:id/versions',
          name: 'content.versions',
          component: () => import('@/modules/content/pages/ContentVersionHistoryPage.vue'),
          meta: { title: 'Content Version History', requiresAuth: true },
        },
        {
          path: 'content/:id/compare',
          name: 'content.compare',
          component: () => import('@/modules/content/pages/ContentVersionComparePage.vue'),
          meta: { title: 'Compare Content Versions', requiresAuth: true },
        },
        {
          path: 'customers',
          name: 'customers.index',
          component: () => import('@/modules/customers/pages/CustomersListPage.vue'),
          meta: { title: 'Customers', requiresAuth: true },
        },
        {
          path: 'support',
          name: 'support.dashboard',
          component: () => import('@/modules/support/pages/SupportDashboardPage.vue'),
          meta: { title: 'Support Center', requiresAuth: true },
        },
        {
          path: 'compliance',
          name: 'compliance.dashboard',
          component: () => import('@/modules/compliance/pages/ComplianceDashboardPage.vue'),
          meta: { title: 'Compliance Center', requiresAuth: true },
        },
        {
          path: 'compliance/cases',
          name: 'compliance.cases.index',
          component: () => import('@/modules/compliance/pages/CasesListPage.vue'),
          meta: { title: 'Compliance Cases', requiresAuth: true },
        },
        {
          path: 'compliance/cases/create',
          name: 'compliance.cases.create',
          component: () => import('@/modules/compliance/pages/CreateCasePage.vue'),
          meta: { title: 'Create Compliance Case', requiresAuth: true },
        },
        {
          path: 'compliance/cases/:id',
          name: 'compliance.cases.show',
          component: () => import('@/modules/compliance/pages/CaseDetailsPage.vue'),
          meta: { title: 'Compliance Case Details', requiresAuth: true },
        },
        {
          path: 'compliance/cases/:id/edit',
          name: 'compliance.cases.edit',
          component: () => import('@/modules/compliance/pages/EditCasePage.vue'),
          meta: { title: 'Edit Compliance Case', requiresAuth: true },
        },
        {
          path: 'compliance/privacy',
          name: 'compliance.privacy.dashboard',
          component: () => import('@/modules/compliance/pages/PrivacyDashboardPage.vue'),
          meta: { title: 'Privacy Request Center', requiresAuth: true },
        },
        {
          path: 'compliance/privacy/requests',
          name: 'compliance.privacy.index',
          component: () => import('@/modules/compliance/pages/PrivacyRequestsListPage.vue'),
          meta: { title: 'Privacy Requests', requiresAuth: true },
        },
        {
          path: 'compliance/privacy/requests/create',
          name: 'compliance.privacy.create',
          component: () => import('@/modules/compliance/pages/CreatePrivacyRequestPage.vue'),
          meta: { title: 'Create Privacy Request', requiresAuth: true },
        },
        {
          path: 'compliance/privacy/requests/:id',
          name: 'compliance.privacy.show',
          component: () => import('@/modules/compliance/pages/PrivacyRequestDetailsPage.vue'),
          meta: { title: 'Privacy Request Details', requiresAuth: true },
        },
        {
          path: 'compliance/privacy/requests/:id/verify',
          name: 'compliance.privacy.verify',
          component: () => import('@/modules/compliance/pages/PrivacyVerificationPage.vue'),
          meta: { title: 'Verify Privacy Request', requiresAuth: true },
        },
        {
          path: 'compliance/consents',
          name: 'compliance.consents.dashboard',
          component: () => import('@/modules/compliance/pages/ConsentDashboardPage.vue'),
          meta: { title: 'Consent Management', requiresAuth: true },
        },
        {
          path: 'compliance/consents/records',
          name: 'compliance.consents.index',
          component: () => import('@/modules/compliance/pages/ConsentsListPage.vue'),
          meta: { title: 'Consent Records', requiresAuth: true },
        },
        {
          path: 'compliance/consents/create',
          name: 'compliance.consents.create',
          component: () => import('@/modules/compliance/pages/CreateConsentPage.vue'),
          meta: { title: 'Record Consent', requiresAuth: true },
        },
        {
          path: 'compliance/consents/preferences',
          name: 'compliance.consents.preferences',
          component: () => import('@/modules/compliance/pages/ConsentPreferenceCenterPage.vue'),
          meta: { title: 'Preference Center', requiresAuth: true },
        },
        {
          path: 'compliance/consents/history',
          name: 'compliance.consents.history',
          component: () => import('@/modules/compliance/pages/ConsentHistoryPage.vue'),
          meta: { title: 'Consent History', requiresAuth: true },
        },
        {
          path: 'compliance/consents/audit',
          name: 'compliance.consents.audit',
          component: () => import('@/modules/compliance/pages/ConsentAuditPage.vue'),
          meta: { title: 'Consent Audit', requiresAuth: true },
        },
        {
          path: 'compliance/consents/records/:id',
          name: 'compliance.consents.show',
          component: () => import('@/modules/compliance/pages/ConsentDetailsPage.vue'),
          meta: { title: 'Consent Details', requiresAuth: true },
        },
        {
          path: 'compliance/breaches',
          name: 'compliance.breaches.dashboard',
          component: () => import('@/modules/compliance/pages/BreachDashboardPage.vue'),
          meta: { title: 'Data Breach Dashboard', requiresAuth: true },
        },
        {
          path: 'compliance/breaches/incidents',
          name: 'compliance.breaches.index',
          component: () => import('@/modules/compliance/pages/BreachesListPage.vue'),
          meta: { title: 'Data Breaches', requiresAuth: true },
        },
        {
          path: 'compliance/breaches/create',
          name: 'compliance.breaches.create',
          component: () => import('@/modules/compliance/pages/CreateBreachPage.vue'),
          meta: { title: 'Report Data Breach', requiresAuth: true },
        },
        {
          path: 'compliance/breaches/risk-matrix',
          name: 'compliance.breaches.risk',
          component: () => import('@/modules/compliance/pages/BreachRiskMatrixPage.vue'),
          meta: { title: 'Breach Risk Matrix', requiresAuth: true },
        },
        {
          path: 'compliance/breaches/notifications',
          name: 'compliance.breaches.notifications',
          component: () => import('@/modules/compliance/pages/BreachNotificationCenterPage.vue'),
          meta: { title: 'Breach Notification Center', requiresAuth: true },
        },
        {
          path: 'compliance/breaches/reports',
          name: 'compliance.breaches.reports',
          component: () => import('@/modules/compliance/pages/BreachReportsPage.vue'),
          meta: { title: 'Breach Reports', requiresAuth: true },
        },
        {
          path: 'compliance/breaches/incidents/:id',
          name: 'compliance.breaches.show',
          component: () => import('@/modules/compliance/pages/BreachDetailsPage.vue'),
          meta: { title: 'Breach Details', requiresAuth: true },
        },
        {
          path: 'compliance/breaches/incidents/:id/affected-users',
          name: 'compliance.breaches.affected',
          component: () => import('@/modules/compliance/pages/BreachAffectedUsersPage.vue'),
          meta: { title: 'Affected Users', requiresAuth: true },
        },
        {
          path: 'compliance/dpia',
          name: 'compliance.dpia.dashboard',
          component: () => import('@/modules/compliance/pages/DpiaDashboardPage.vue'),
          meta: { title: 'DPIA & Risk Dashboard', requiresAuth: true },
        },
        {
          path: 'compliance/dpia/history',
          name: 'compliance.dpia.history',
          component: () => import('@/modules/compliance/pages/DpiaHistoryPage.vue'),
          meta: { title: 'DPIA Assessment History', requiresAuth: true },
        },
        {
          path: 'compliance/dpia/wizard',
          name: 'compliance.dpia.wizard',
          component: () => import('@/modules/compliance/pages/DpiaWizardPage.vue'),
          meta: { title: 'DPIA Wizard', requiresAuth: true },
        },
        {
          path: 'compliance/dpia/wizard/:id',
          name: 'compliance.dpia.wizard.edit',
          component: () => import('@/modules/compliance/pages/DpiaWizardPage.vue'),
          meta: { title: 'DPIA Wizard', requiresAuth: true },
        },
        {
          path: 'compliance/dpia/risk-matrix',
          name: 'compliance.dpia.risk',
          component: () => import('@/modules/compliance/pages/DpiaRiskMatrixPage.vue'),
          meta: { title: 'DPIA Risk Matrix', requiresAuth: true },
        },
        {
          path: 'compliance/dpia/mitigation',
          name: 'compliance.dpia.mitigation',
          component: () => import('@/modules/compliance/pages/DpiaMitigationTrackerPage.vue'),
          meta: { title: 'Mitigation Tracker', requiresAuth: true },
        },
        {
          path: 'compliance/dpia/assessments/:id',
          name: 'compliance.dpia.show',
          component: () => import('@/modules/compliance/pages/DpiaDetailsPage.vue'),
          meta: { title: 'DPIA Details', requiresAuth: true },
        },
        {
          path: 'compliance/policies',
          name: 'compliance.policies.dashboard',
          component: () => import('@/modules/compliance/pages/PolicyDashboardPage.vue'),
          meta: { title: 'Policy Dashboard', requiresAuth: true },
        },
        {
          path: 'compliance/policies/list',
          name: 'compliance.policies.index',
          component: () => import('@/modules/compliance/pages/PoliciesListPage.vue'),
          meta: { title: 'Policy Documents', requiresAuth: true },
        },
        {
          path: 'compliance/policies/create',
          name: 'compliance.policies.create',
          component: () => import('@/modules/compliance/pages/CreatePolicyPage.vue'),
          meta: { title: 'Create Policy', requiresAuth: true },
        },
        {
          path: 'compliance/policies/approvals',
          name: 'compliance.policies.approvals',
          component: () => import('@/modules/compliance/pages/PolicyApprovalQueuePage.vue'),
          meta: { title: 'Policy Approvals', requiresAuth: true },
        },
        {
          path: 'compliance/policies/:id/versions',
          name: 'compliance.policies.versions',
          component: () => import('@/modules/compliance/pages/PolicyVersionTimelinePage.vue'),
          meta: { title: 'Policy Version Timeline', requiresAuth: true },
        },
        {
          path: 'compliance/policies/:id/compare',
          name: 'compliance.policies.compare',
          component: () => import('@/modules/compliance/pages/PolicyVersionComparePage.vue'),
          meta: { title: 'Compare Policy Versions', requiresAuth: true },
        },
        {
          path: 'compliance/policies/:id',
          name: 'compliance.policies.show',
          component: () => import('@/modules/compliance/pages/PolicyDetailsPage.vue'),
          meta: { title: 'Policy Details', requiresAuth: true },
        },
        {
          path: 'compliance/analytics',
          name: 'compliance.analytics.dashboard',
          component: () => import('@/modules/compliance/pages/ComplianceAnalyticsDashboardPage.vue'),
          meta: { title: 'Compliance Analytics', requiresAuth: true },
        },
        {
          path: 'compliance/analytics/risks',
          name: 'compliance.analytics.risks',
          component: () => import('@/modules/compliance/pages/ComplianceRiskChartsPage.vue'),
          meta: { title: 'Compliance Risk Charts', requiresAuth: true },
        },
        {
          path: 'compliance/analytics/reports/gdpr',
          name: 'compliance.analytics.gdpr',
          component: () => import('@/modules/compliance/pages/ComplianceGdprReportPage.vue'),
          meta: { title: 'GDPR Reports', requiresAuth: true },
        },
        {
          path: 'compliance/analytics/reports/consent',
          name: 'compliance.analytics.consent',
          component: () => import('@/modules/compliance/pages/ComplianceConsentReportPage.vue'),
          meta: { title: 'Consent Reports', requiresAuth: true },
        },
        {
          path: 'compliance/analytics/reports/audit',
          name: 'compliance.analytics.audit',
          component: () => import('@/modules/compliance/pages/ComplianceAuditReportPage.vue'),
          meta: { title: 'Audit Reports', requiresAuth: true },
        },
        {
          path: 'support/tickets',
          name: 'support.tickets.index',
          component: () => import('@/modules/support/pages/TicketsListPage.vue'),
          meta: { title: 'Support Tickets', requiresAuth: true },
        },
        {
          path: 'support/tickets/board',
          name: 'support.tickets.board',
          component: () => import('@/modules/support/pages/TicketKanbanPage.vue'),
          meta: { title: 'Support Kanban', requiresAuth: true },
        },
        {
          path: 'support/tickets/queue',
          name: 'support.tickets.queue',
          component: () => import('@/modules/support/pages/TicketQueuePage.vue'),
          meta: { title: 'Support Queue', requiresAuth: true },
        },
        {
          path: 'support/tickets/assignment',
          name: 'support.tickets.assignment',
          component: () => import('@/modules/support/pages/TicketAssignmentPage.vue'),
          meta: { title: 'Ticket Assignment', requiresAuth: true },
        },
        {
          path: 'support/sla',
          name: 'support.sla.dashboard',
          component: () => import('@/modules/support/pages/SlaDashboardPage.vue'),
          meta: { title: 'SLA Dashboard', requiresAuth: true },
        },
        {
          path: 'support/sla/escalations',
          name: 'support.sla.escalations',
          component: () => import('@/modules/support/pages/SlaEscalationQueuePage.vue'),
          meta: { title: 'Escalation Queue', requiresAuth: true },
        },
        {
          path: 'support/sla/violations',
          name: 'support.sla.violations',
          component: () => import('@/modules/support/pages/SlaViolationsPage.vue'),
          meta: { title: 'SLA Violations', requiresAuth: true },
        },
        {
          path: 'support/sla/policies',
          name: 'support.sla.policies',
          component: () => import('@/modules/support/pages/SlaPoliciesPage.vue'),
          meta: { title: 'SLA Policies', requiresAuth: true },
        },
        {
          path: 'support/sla/calendars',
          name: 'support.sla.calendars',
          component: () => import('@/modules/support/pages/SlaCalendarsPage.vue'),
          meta: { title: 'SLA Calendars', requiresAuth: true },
        },
        {
          path: 'support/knowledge',
          name: 'support.knowledge.center',
          component: () => import('@/modules/support/pages/KnowledgeCenterPage.vue'),
          meta: { title: 'Knowledge Center', requiresAuth: true },
        },
        {
          path: 'support/knowledge/articles',
          name: 'support.knowledge.index',
          component: () => import('@/modules/support/pages/KnowledgeArticlesPage.vue'),
          meta: { title: 'Knowledge Articles', requiresAuth: true },
        },
        {
          path: 'support/knowledge/articles/create',
          name: 'support.knowledge.create',
          component: () => import('@/modules/support/pages/KnowledgeArticleFormPage.vue'),
          meta: { title: 'Create Knowledge Article', requiresAuth: true },
        },
        {
          path: 'support/knowledge/articles/:id/edit',
          name: 'support.knowledge.edit',
          component: () => import('@/modules/support/pages/KnowledgeArticleFormPage.vue'),
          meta: { title: 'Edit Knowledge Article', requiresAuth: true },
        },
        {
          path: 'support/knowledge/articles/:id',
          name: 'support.knowledge.show',
          component: () => import('@/modules/support/pages/KnowledgeArticleViewPage.vue'),
          meta: { title: 'Knowledge Article', requiresAuth: true },
        },
        {
          path: 'support/canned-responses',
          name: 'support.canned.index',
          component: () => import('@/modules/support/pages/CannedResponsesPage.vue'),
          meta: { title: 'Canned Responses', requiresAuth: true },
        },
        {
          path: 'notifications',
          name: 'notifications.dashboard',
          component: () => import('@/modules/notifications/pages/NotificationDashboardPage.vue'),
          meta: { title: 'Notification Dashboard', requiresAuth: true },
        },
        {
          path: 'notifications/center',
          name: 'notifications.center',
          component: () => import('@/modules/notifications/pages/NotificationCenterPage.vue'),
          meta: { title: 'Notification Center', requiresAuth: true },
        },
        {
          path: 'notifications/unread',
          name: 'notifications.unread',
          component: () => import('@/modules/notifications/pages/NotificationUnreadPage.vue'),
          meta: { title: 'Unread Notifications', requiresAuth: true },
        },
        {
          path: 'notifications/history',
          name: 'notifications.history',
          component: () => import('@/modules/notifications/pages/NotificationHistoryPage.vue'),
          meta: { title: 'Notification History', requiresAuth: true },
        },
        {
          path: 'notifications/preferences',
          name: 'notifications.preferences',
          component: () => import('@/modules/notifications/pages/NotificationPreferencesPage.vue'),
          meta: { title: 'Notification Preferences', requiresAuth: true },
        },
        {
          path: 'notifications/templates',
          name: 'notifications.templates',
          component: () => import('@/modules/notifications/pages/NotificationTemplatesPage.vue'),
          meta: { title: 'Notification Templates', requiresAuth: true },
        },
        {
          path: 'notifications/templates/approvals',
          name: 'notifications.templates.approvals',
          component: () => import('@/modules/notifications/pages/NotificationTemplateApprovalsPage.vue'),
          meta: { title: 'Template Approvals', requiresAuth: true },
        },
        {
          path: 'notifications/templates/create',
          name: 'notifications.templates.create',
          component: () => import('@/modules/notifications/pages/NotificationTemplateEditorPage.vue'),
          meta: { title: 'Create Notification Template', requiresAuth: true },
        },
        {
          path: 'notifications/templates/:id/edit',
          name: 'notifications.templates.edit',
          component: () => import('@/modules/notifications/pages/NotificationTemplateEditorPage.vue'),
          meta: { title: 'Edit Notification Template', requiresAuth: true },
        },
        {
          path: 'notifications/templates/:id/preview',
          name: 'notifications.templates.preview',
          component: () => import('@/modules/notifications/pages/NotificationTemplatePreviewPage.vue'),
          meta: { title: 'Template Preview', requiresAuth: true },
        },
        {
          path: 'notifications/templates/:id/versions',
          name: 'notifications.templates.versions',
          component: () => import('@/modules/notifications/pages/NotificationTemplateVersionsPage.vue'),
          meta: { title: 'Template Versions', requiresAuth: true },
        },
        {
          path: 'notifications/templates/:id/compare',
          name: 'notifications.templates.compare',
          component: () => import('@/modules/notifications/pages/NotificationTemplateComparePage.vue'),
          meta: { title: 'Compare Template Versions', requiresAuth: true },
        },
        {
          path: 'notifications/delivery-logs',
          name: 'notifications.logs',
          component: () => import('@/modules/notifications/pages/NotificationDeliveryLogsPage.vue'),
          meta: { title: 'Notification Logs', requiresAuth: true },
        },
        {
          path: 'automation',
          name: 'automation.dashboard',
          component: () => import('@/modules/automation/pages/AutomationDashboardPage.vue'),
          meta: { title: 'Automation Engine', requiresAuth: true },
        },
        {
          path: 'automation/rules',
          name: 'automation.rules',
          component: () => import('@/modules/automation/pages/AutomationRulesPage.vue'),
          meta: { title: 'Automation Rules', requiresAuth: true },
        },
        {
          path: 'automation/rules/create',
          name: 'automation.rules.create',
          component: () => import('@/modules/automation/pages/AutomationRuleBuilderPage.vue'),
          meta: { title: 'Create Automation Rule', requiresAuth: true },
        },
        {
          path: 'automation/rules/:id/edit',
          name: 'automation.rules.edit',
          component: () => import('@/modules/automation/pages/AutomationRuleBuilderPage.vue'),
          meta: { title: 'Edit Automation Rule', requiresAuth: true },
        },
        {
          path: 'automation/history',
          name: 'automation.history',
          component: () => import('@/modules/automation/pages/AutomationHistoryPage.vue'),
          meta: { title: 'Automation History', requiresAuth: true },
        },
        {
          path: 'workflows',
          name: 'workflows.dashboard',
          component: () => import('@/modules/workflows/pages/WorkflowDashboardPage.vue'),
          meta: { title: 'Workflow Engine', requiresAuth: true },
        },
        {
          path: 'workflows/designer',
          name: 'workflows.designer',
          component: () => import('@/modules/workflows/pages/WorkflowDesignerListPage.vue'),
          meta: { title: 'Workflow Designer', requiresAuth: true },
        },
        {
          path: 'workflows/designer/create',
          name: 'workflows.designer.create',
          component: () => import('@/modules/workflows/pages/WorkflowDesignerPage.vue'),
          meta: { title: 'Create Workflow', requiresAuth: true },
        },
        {
          path: 'workflows/designer/:id/edit',
          name: 'workflows.designer.edit',
          component: () => import('@/modules/workflows/pages/WorkflowDesignerPage.vue'),
          meta: { title: 'Edit Workflow', requiresAuth: true },
        },
        {
          path: 'workflows/monitor',
          name: 'workflows.monitor',
          component: () => import('@/modules/workflows/pages/WorkflowMonitorPage.vue'),
          meta: { title: 'Workflow Monitor', requiresAuth: true },
        },
        {
          path: 'workflows/queue',
          name: 'workflows.queue',
          component: () => import('@/modules/workflows/pages/WorkflowApprovalQueuePage.vue'),
          meta: { title: 'Workflow Approval Queue', requiresAuth: true },
        },
        {
          path: 'workflows/history',
          name: 'workflows.history',
          component: () => import('@/modules/workflows/pages/WorkflowHistoryPage.vue'),
          meta: { title: 'Workflow History', requiresAuth: true },
        },
        {
          path: 'workflows/instances/:id',
          name: 'workflows.instances.show',
          component: () => import('@/modules/workflows/pages/WorkflowInstancePage.vue'),
          meta: { title: 'Workflow Instance', requiresAuth: true },
        },
        {
          path: 'scheduler',
          name: 'scheduler.dashboard',
          component: () => import('@/modules/scheduler/pages/SchedulerDashboardPage.vue'),
          meta: { title: 'Enterprise Scheduler', requiresAuth: true },
        },
        {
          path: 'scheduler/jobs',
          name: 'scheduler.jobs',
          component: () => import('@/modules/scheduler/pages/SchedulerJobsPage.vue'),
          meta: { title: 'Scheduled Jobs', requiresAuth: true },
        },
        {
          path: 'scheduler/jobs/create',
          name: 'scheduler.jobs.create',
          component: () => import('@/modules/scheduler/pages/SchedulerJobFormPage.vue'),
          meta: { title: 'Create Scheduled Job', requiresAuth: true },
        },
        {
          path: 'scheduler/jobs/:id/edit',
          name: 'scheduler.jobs.edit',
          component: () => import('@/modules/scheduler/pages/SchedulerJobFormPage.vue'),
          meta: { title: 'Edit Scheduled Job', requiresAuth: true },
        },
        {
          path: 'scheduler/history',
          name: 'scheduler.history',
          component: () => import('@/modules/scheduler/pages/SchedulerHistoryPage.vue'),
          meta: { title: 'Scheduler History', requiresAuth: true },
        },
        {
          path: 'scheduler/running',
          name: 'scheduler.running',
          component: () => import('@/modules/scheduler/pages/SchedulerRunningPage.vue'),
          meta: { title: 'Running Jobs', requiresAuth: true },
        },
        {
          path: 'scheduler/failed',
          name: 'scheduler.failed',
          component: () => import('@/modules/scheduler/pages/SchedulerFailedPage.vue'),
          meta: { title: 'Failed Jobs', requiresAuth: true },
        },
        {
          path: 'scheduler/logs',
          name: 'scheduler.logs',
          component: () => import('@/modules/scheduler/pages/SchedulerLogsPage.vue'),
          meta: { title: 'Scheduler Logs', requiresAuth: true },
        },
        {
          path: 'scheduler/statistics',
          name: 'scheduler.statistics',
          component: () => import('@/modules/scheduler/pages/SchedulerStatisticsPage.vue'),
          meta: { title: 'Scheduler Statistics', requiresAuth: true },
        },
        {
          path: 'ai',
          name: 'ai.dashboard',
          component: () => import('@/modules/ai/pages/AiDashboardPage.vue'),
          meta: { title: 'AI Assistant', requiresAuth: true },
        },
        {
          path: 'ai/settings',
          name: 'ai.settings',
          component: () => import('@/modules/ai/pages/AiSettingsPage.vue'),
          meta: { title: 'AI Settings', requiresAuth: true },
        },
        {
          path: 'ai/prompts',
          name: 'ai.prompts',
          component: () => import('@/modules/ai/pages/AiPromptsPage.vue'),
          meta: { title: 'Prompt Manager', requiresAuth: true },
        },
        {
          path: 'ai/conversations',
          name: 'ai.conversations',
          component: () => import('@/modules/ai/pages/AiConversationsPage.vue'),
          meta: { title: 'AI Conversations', requiresAuth: true },
        },
        {
          path: 'ai/analytics',
          name: 'ai.analytics',
          component: () => import('@/modules/ai/pages/AiAnalyticsPage.vue'),
          meta: { title: 'AI Usage Analytics', requiresAuth: true },
        },
        {
          path: 'ai/logs',
          name: 'ai.logs',
          component: () => import('@/modules/ai/pages/AiLogsPage.vue'),
          meta: { title: 'AI Logs', requiresAuth: true },
        },
        {
          path: 'analytics',
          name: 'analytics.dashboard',
          component: () => import('@/modules/analytics/pages/AnalyticsDashboardPage.vue'),
          meta: { title: 'Analytics Overview', requiresAuth: true },
        },
        {
          path: 'analytics/dashboards',
          name: 'analytics.dashboards',
          component: () => import('@/modules/analytics/pages/AnalyticsDashboardsPage.vue'),
          meta: { title: 'Analytics Dashboards', requiresAuth: true },
        },
        {
          path: 'analytics/dashboards/:uuid/designer',
          name: 'analytics.dashboards.designer',
          component: () => import('@/modules/analytics/pages/AnalyticsDashboardDesignerPage.vue'),
          meta: { title: 'Dashboard Designer', requiresAuth: true },
        },
        {
          path: 'analytics/dashboards/:uuid',
          name: 'analytics.dashboards.show',
          component: () => import('@/modules/analytics/pages/AnalyticsDashboardViewPage.vue'),
          meta: { title: 'Analytics Dashboard', requiresAuth: true },
        },
        {
          path: 'analytics/templates',
          name: 'analytics.templates',
          component: () => import('@/modules/analytics/pages/AnalyticsTemplatesPage.vue'),
          meta: { title: 'Dashboard Templates', requiresAuth: true },
        },
        {
          path: 'analytics/reports',
          name: 'analytics.reports',
          component: () => import('@/modules/analytics/pages/AnalyticsReportsPage.vue'),
          meta: { title: 'Report Builder', requiresAuth: true },
        },
        {
          path: 'analytics/reports/:uuid/designer',
          name: 'analytics.reports.designer',
          component: () => import('@/modules/analytics/pages/AnalyticsReportDesignerPage.vue'),
          meta: { title: 'Report Designer', requiresAuth: true },
        },
        {
          path: 'analytics/saved-reports',
          name: 'analytics.saved-reports',
          component: () => import('@/modules/analytics/pages/AnalyticsSavedReportsPage.vue'),
          meta: { title: 'Saved Reports', requiresAuth: true },
        },
        {
          path: 'analytics/saved-views',
          name: 'analytics.saved-views',
          component: () => import('@/modules/analytics/pages/AnalyticsSavedViewsPage.vue'),
          meta: { title: 'Saved Views', requiresAuth: true },
        },
        {
          path: 'analytics/events',
          name: 'analytics.events',
          component: () => import('@/modules/analytics/pages/AnalyticsEventsPage.vue'),
          meta: { title: 'Analytics Events', requiresAuth: true },
        },
        {
          path: 'analytics/business',
          name: 'analytics.business',
          component: () => import('@/modules/analytics/pages/BusinessDashboardPage.vue'),
          meta: { title: 'Business Dashboard', requiresAuth: true },
        },
        {
          path: 'analytics/business/customers',
          name: 'analytics.business.customers',
          component: () => import('@/modules/analytics/pages/CustomerBusinessDashboardPage.vue'),
          meta: { title: 'Customer Dashboard', requiresAuth: true },
        },
        {
          path: 'analytics/business/revenue',
          name: 'analytics.business.revenue',
          component: () => import('@/modules/analytics/pages/RevenueDashboardPage.vue'),
          meta: { title: 'Revenue Dashboard', requiresAuth: true },
        },
        {
          path: 'analytics/business/applications',
          name: 'analytics.business.applications',
          component: () => import('@/modules/analytics/pages/ApplicationBusinessDashboardPage.vue'),
          meta: { title: 'Application Dashboard', requiresAuth: true },
        },
        {
          path: 'analytics/business/growth',
          name: 'analytics.business.growth',
          component: () => import('@/modules/analytics/pages/GrowthForecastPage.vue'),
          meta: { title: 'Growth & Forecast', requiresAuth: true },
        },
        {
          path: 'analytics/executive',
          name: 'analytics.executive',
          component: () => import('@/modules/analytics/pages/ExecutiveDashboardPage.vue'),
          props: { dashboardType: 'ceo' },
          meta: { title: 'CEO Dashboard', requiresAuth: true, executiveType: 'ceo' },
        },
        {
          path: 'analytics/executive/admin',
          name: 'analytics.executive.admin',
          component: () => import('@/modules/analytics/pages/ExecutiveDashboardPage.vue'),
          props: { dashboardType: 'admin' },
          meta: { title: 'Admin Dashboard', requiresAuth: true, executiveType: 'admin' },
        },
        {
          path: 'analytics/executive/operations',
          name: 'analytics.executive.operations',
          component: () => import('@/modules/analytics/pages/ExecutiveDashboardPage.vue'),
          props: { dashboardType: 'operations' },
          meta: { title: 'Operations Dashboard', requiresAuth: true, executiveType: 'operations' },
        },
        {
          path: 'analytics/executive/compliance',
          name: 'analytics.executive.compliance',
          component: () => import('@/modules/analytics/pages/ExecutiveDashboardPage.vue'),
          props: { dashboardType: 'compliance' },
          meta: { title: 'Compliance Dashboard', requiresAuth: true, executiveType: 'compliance' },
        },
        {
          path: 'analytics/executive/support',
          name: 'analytics.executive.support',
          component: () => import('@/modules/analytics/pages/ExecutiveDashboardPage.vue'),
          props: { dashboardType: 'support' },
          meta: { title: 'Support Dashboard', requiresAuth: true, executiveType: 'support' },
        },
        {
          path: 'analytics/executive/customer',
          name: 'analytics.executive.customer',
          component: () => import('@/modules/analytics/pages/ExecutiveDashboardPage.vue'),
          props: { dashboardType: 'customer' },
          meta: { title: 'Customer Dashboard', requiresAuth: true, executiveType: 'customer' },
        },
        {
          path: 'analytics/executive/scorecards',
          name: 'analytics.executive.scorecards',
          component: () => import('@/modules/analytics/pages/ExecutiveScorecardsPage.vue'),
          meta: { title: 'Business Scorecards', requiresAuth: true },
        },
        {
          path: 'analytics/executive/trends',
          name: 'analytics.executive.trends',
          component: () => import('@/modules/analytics/pages/ExecutiveTrendsPage.vue'),
          meta: { title: 'Executive Trends', requiresAuth: true },
        },
        {
          path: 'analytics/executive/forecast',
          name: 'analytics.executive.forecast',
          component: () => import('@/modules/analytics/pages/ExecutiveForecastPage.vue'),
          meta: { title: 'Executive Forecast', requiresAuth: true },
        },
        {
          path: 'analytics/security',
          name: 'analytics.security',
          component: () => import('@/modules/analytics/pages/SecurityDashboardPage.vue'),
          meta: { title: 'Security Dashboard', requiresAuth: true },
        },
        {
          path: 'analytics/security/audit',
          name: 'analytics.security.audit',
          component: () => import('@/modules/analytics/pages/AuditDashboardPage.vue'),
          meta: { title: 'Audit Dashboard', requiresAuth: true },
        },
        {
          path: 'analytics/security/timeline',
          name: 'analytics.security.timeline',
          component: () => import('@/modules/analytics/pages/ThreatTimelinePage.vue'),
          meta: { title: 'Threat Timeline', requiresAuth: true },
        },
        {
          path: 'analytics/security/risk',
          name: 'analytics.security.risk',
          component: () => import('@/modules/analytics/pages/RiskIndicatorsPage.vue'),
          meta: { title: 'Risk Indicators', requiresAuth: true },
        },
        {
          path: 'analytics/security/heatmap',
          name: 'analytics.security.heatmap',
          component: () => import('@/modules/analytics/pages/SecurityHeatmapPage.vue'),
          meta: { title: 'Activity Heatmap', requiresAuth: true },
        },
        {
          path: 'analytics/security/export',
          name: 'analytics.security.export',
          component: () => import('@/modules/analytics/pages/SecurityExportPage.vue'),
          meta: { title: 'Export Security Report', requiresAuth: true },
        },
        {
          path: 'analytics/operational',
          name: 'analytics.operational',
          component: () => import('@/modules/analytics/pages/OperationalAnalyticsPage.vue'),
          meta: { title: 'Operational Analytics', requiresAuth: true },
        },
        {
          path: 'analytics/delivery',
          name: 'analytics.delivery',
          component: () => import('@/modules/analytics/pages/DeliveryReportsPage.vue'),
          meta: { title: 'Delivery Reports', requiresAuth: true },
        },
        {
          path: 'analytics/automation',
          name: 'analytics.automation',
          component: () => import('@/modules/analytics/pages/AutomationReportsPage.vue'),
          meta: { title: 'Automation Reports', requiresAuth: true },
        },
        {
          path: 'analytics/workflows',
          name: 'analytics.workflows',
          component: () => import('@/modules/analytics/pages/WorkflowReportsPage.vue'),
          meta: { title: 'Workflow Reports', requiresAuth: true },
        },
        {
          path: 'analytics/ai',
          name: 'analytics.ai',
          component: () => import('@/modules/analytics/pages/AiUsageReportsPage.vue'),
          meta: { title: 'AI Usage Analytics', requiresAuth: true },
        },
        {
          path: 'support/tickets/create',
          name: 'support.tickets.create',
          component: () => import('@/modules/support/pages/CreateTicketPage.vue'),
          meta: { title: 'Create Support Ticket', requiresAuth: true },
        },
        {
          path: 'support/tickets/:id',
          name: 'support.tickets.show',
          component: () => import('@/modules/support/pages/ViewTicketPage.vue'),
          meta: { title: 'Support Ticket Details', requiresAuth: true },
        },
        {
          path: 'customers/create',
          name: 'customers.create',
          component: () => import('@/modules/customers/pages/CreateCustomerPage.vue'),
          meta: { title: 'Create Customer', requiresAuth: true },
        },
        {
          path: 'customers/:id',
          name: 'customers.show',
          component: () => import('@/modules/customers/pages/ViewCustomerPage.vue'),
          meta: { title: 'Customer Details', requiresAuth: true },
        },
        {
          path: 'customers/:id/edit',
          name: 'customers.edit',
          component: () => import('@/modules/customers/pages/EditCustomerPage.vue'),
          meta: { title: 'Edit Customer', requiresAuth: true },
        },
        {
          path: 'customers/:id/contacts',
          name: 'customers.contacts',
          component: () => import('@/modules/customers/pages/ContactsListPage.vue'),
          meta: { title: 'Customer Contacts', requiresAuth: true },
        },
        {
          path: 'customers/:id/contacts/create',
          name: 'customers.contacts.create',
          redirect: (to) => ({ name: 'customers.contacts', params: { id: to.params.id } }),
        },
        {
          path: 'customers/:id/contacts/:contactId',
          name: 'customers.contacts.show',
          component: () => import('@/modules/customers/pages/ViewContactPage.vue'),
          meta: { title: 'Contact Details', requiresAuth: true },
        },
        {
          path: 'customers/:id/contacts/:contactId/edit',
          name: 'customers.contacts.edit',
          redirect: (to) => ({
            name: 'customers.contacts.show',
            params: { id: to.params.id, contactId: to.params.contactId },
          }),
        },
        {
          path: 'customers/:id/applications',
          name: 'customers.applications',
          component: () => import('@/modules/customers/pages/AssignedApplicationsPage.vue'),
          meta: { title: 'Assigned Applications', requiresAuth: true },
        },
        {
          path: 'customers/:id/applications/history',
          name: 'customers.applications.history',
          component: () => import('@/modules/customers/pages/ApplicationHistoryPage.vue'),
          meta: { title: 'Application History', requiresAuth: true },
        },
        {
          path: 'customers/:id/applications/create',
          name: 'customers.applications.create',
          redirect: (to) => ({ name: 'customers.applications', params: { id: to.params.id } }),
        },
        {
          path: 'customers/:id/applications/:assignmentId',
          name: 'customers.applications.show',
          component: () => import('@/modules/customers/pages/ViewAssignmentPage.vue'),
          meta: { title: 'Assignment Details', requiresAuth: true },
        },
        {
          path: 'customers/:id/applications/:assignmentId/edit',
          name: 'customers.applications.edit',
          redirect: (to) => ({
            name: 'customers.applications.show',
            params: { id: to.params.id, assignmentId: to.params.assignmentId },
          }),
        },
        {
          path: 'customers/:id/subscriptions',
          name: 'customers.subscriptions',
          component: () => import('@/modules/customers/pages/SubscriptionDashboardPage.vue'),
          meta: { title: 'Subscriptions', requiresAuth: true },
        },
        {
          path: 'customers/:id/subscriptions/create',
          name: 'customers.subscriptions.create',
          redirect: (to) => ({ name: 'customers.subscriptions', params: { id: to.params.id } }),
        },
        {
          path: 'customers/:id/subscriptions/:subscriptionId',
          name: 'customers.subscriptions.show',
          component: () => import('@/modules/customers/pages/ViewSubscriptionPage.vue'),
          meta: { title: 'Subscription Details', requiresAuth: true },
        },
        {
          path: 'customers/:id/subscriptions/:subscriptionId/edit',
          name: 'customers.subscriptions.edit',
          redirect: (to) => ({
            name: 'customers.subscriptions.show',
            params: { id: to.params.id, subscriptionId: to.params.subscriptionId },
          }),
        },
        {
          path: 'customers/:id/licenses',
          name: 'customers.licenses',
          component: () => import('@/modules/customers/pages/LicensesListPage.vue'),
          meta: { title: 'Licenses', requiresAuth: true },
        },
        {
          path: 'customers/:id/licenses/history',
          name: 'customers.licenses.history',
          component: () => import('@/modules/customers/pages/LicenseHistoryPage.vue'),
          meta: { title: 'License History', requiresAuth: true },
        },
        {
          path: 'customers/:id/licenses/create',
          name: 'customers.licenses.create',
          redirect: (to) => ({
            name: 'customers.licenses',
            params: { id: to.params.id },
            query: to.query,
          }),
        },
        {
          path: 'customers/:id/licenses/:licenseId',
          name: 'customers.licenses.show',
          component: () => import('@/modules/customers/pages/ViewLicensePage.vue'),
          meta: { title: 'License Details', requiresAuth: true },
        },
        {
          path: 'customers/:id/licenses/:licenseId/edit',
          name: 'customers.licenses.edit',
          redirect: (to) => ({
            name: 'customers.licenses.show',
            params: { id: to.params.id, licenseId: to.params.licenseId },
          }),
        },
        {
          path: 'customers/:id/documents',
          name: 'customers.documents',
          component: () => import('@/modules/customers/pages/DocumentLibraryPage.vue'),
          meta: { title: 'Document Library', requiresAuth: true },
        },
        {
          path: 'customers/:id/documents/upload',
          name: 'customers.documents.upload',
          redirect: (to) => ({
            name: 'customers.documents',
            params: { id: to.params.id },
            query: to.query,
          }),
        },
        {
          path: 'customers/:id/documents/:documentId',
          name: 'customers.documents.show',
          component: () => import('@/modules/customers/pages/ViewDocumentPage.vue'),
          meta: { title: 'Document Details', requiresAuth: true },
        },
        {
          path: 'customers/:id/documents/:documentId/edit',
          name: 'customers.documents.edit',
          redirect: (to) => ({
            name: 'customers.documents.show',
            params: { id: to.params.id, documentId: to.params.documentId },
          }),
        },
        {
          path: 'customers/:id/communications',
          name: 'customers.communications',
          component: () => import('@/modules/customers/pages/CommunicationCenterPage.vue'),
          meta: { title: 'Communication Center', requiresAuth: true },
        },
        {
          path: 'customers/:id/analytics',
          name: 'customers.analytics',
          component: () => import('@/modules/customers/pages/CustomerAnalyticsDashboardPage.vue'),
          meta: { title: 'Customer Analytics', requiresAuth: true },
        },
        {
          path: 'applications/:id/versions',
          name: 'applications.versions',
          component: () => import('@/modules/applications/pages/VersionsListPage.vue'),
          meta: { title: 'Application Versions', requiresAuth: true },
        },
        {
          path: 'applications/:id/versions/create',
          name: 'applications.versions.create',
          component: () => import('@/modules/applications/pages/CreateVersionPage.vue'),
          meta: { title: 'Create Version', requiresAuth: true },
        },
        {
          path: 'applications/:id/versions/compare',
          name: 'applications.versions.compare',
          component: () => import('@/modules/applications/pages/CompareVersionsPage.vue'),
          meta: { title: 'Compare Versions', requiresAuth: true },
        },
        {
          path: 'applications/:id/versions/timeline',
          name: 'applications.versions.timeline',
          component: () => import('@/modules/applications/pages/VersionTimelinePage.vue'),
          meta: { title: 'Version Timeline', requiresAuth: true },
        },
        {
          path: 'applications/:id/versions/history',
          name: 'applications.versions.history',
          component: () => import('@/modules/applications/pages/VersionHistoryPage.vue'),
          meta: { title: 'Version History', requiresAuth: true },
        },
        {
          path: 'applications/:id/versions/:versionId/edit',
          name: 'applications.versions.edit',
          component: () => import('@/modules/applications/pages/EditVersionPage.vue'),
          meta: { title: 'Edit Version', requiresAuth: true },
        },
        {
          path: 'applications/:id/environments',
          name: 'applications.environments',
          component: () => import('@/modules/applications/pages/EnvironmentsDashboardPage.vue'),
          meta: { title: 'Environments', requiresAuth: true },
        },
        {
          path: 'applications/:id/environments/create',
          name: 'applications.environments.create',
          component: () => import('@/modules/applications/pages/CreateEnvironmentPage.vue'),
          meta: { title: 'Create Environment', requiresAuth: true },
        },
        {
          path: 'applications/:id/environments/:environmentId',
          name: 'applications.environments.show',
          component: () => import('@/modules/applications/pages/ViewEnvironmentPage.vue'),
          meta: { title: 'Environment Details', requiresAuth: true },
        },
        {
          path: 'applications/:id/environments/:environmentId/edit',
          name: 'applications.environments.edit',
          component: () => import('@/modules/applications/pages/EditEnvironmentPage.vue'),
          meta: { title: 'Edit Environment', requiresAuth: true },
        },
        {
          path: 'applications/:id/configurations',
          name: 'applications.configurations',
          component: () => import('@/modules/applications/pages/ConfigurationManagerPage.vue'),
          meta: { title: 'Configuration Manager', requiresAuth: true },
        },
        {
          path: 'applications/:id/configurations/create',
          name: 'applications.configurations.create',
          component: () => import('@/modules/applications/pages/CreateConfigurationPage.vue'),
          meta: { title: 'Create Configuration', requiresAuth: true },
        },
        {
          path: 'applications/:id/configurations/:configurationId/edit',
          name: 'applications.configurations.edit',
          component: () => import('@/modules/applications/pages/EditConfigurationPage.vue'),
          meta: { title: 'Edit Configuration', requiresAuth: true },
        },
        {
          path: 'applications/:id/configurations/:configurationId/flags',
          name: 'applications.configurations.flags',
          component: () => import('@/modules/applications/pages/FeatureFlagsPage.vue'),
          meta: { title: 'Feature Flag Manager', requiresAuth: true },
        },
        {
          path: 'applications/:id/configurations/:configurationId/history',
          name: 'applications.configurations.history',
          component: () => import('@/modules/applications/pages/ConfigurationHistoryPage.vue'),
          meta: { title: 'Configuration History', requiresAuth: true },
        },
        {
          path: 'applications/:id/releases',
          name: 'applications.releases',
          component: () => import('@/modules/applications/pages/ReleaseDashboardPage.vue'),
          meta: { title: 'Release Dashboard', requiresAuth: true },
        },
        {
          path: 'applications/:id/releases/create',
          name: 'applications.releases.create',
          component: () => import('@/modules/applications/pages/CreateReleasePage.vue'),
          meta: { title: 'Plan Release', requiresAuth: true },
        },
        {
          path: 'applications/:id/releases/calendar',
          name: 'applications.releases.calendar',
          component: () => import('@/modules/applications/pages/ReleaseCalendarPage.vue'),
          meta: { title: 'Release Calendar', requiresAuth: true },
        },
        {
          path: 'applications/:id/releases/timeline',
          name: 'applications.releases.timeline',
          component: () => import('@/modules/applications/pages/ReleaseTimelinePage.vue'),
          meta: { title: 'Release Timeline', requiresAuth: true },
        },
        {
          path: 'applications/:id/releases/:releaseId',
          name: 'applications.releases.show',
          component: () => import('@/modules/applications/pages/ReleaseDetailsPage.vue'),
          meta: { title: 'Release Details', requiresAuth: true },
        },
        {
          path: 'applications/:id/releases/:releaseId/approval',
          name: 'applications.releases.approval',
          component: () => import('@/modules/applications/pages/ReleaseApprovalPage.vue'),
          meta: { title: 'Release Approval', requiresAuth: true },
        },
        {
          path: 'applications/:id/monitoring',
          redirect: { name: 'applications.monitoring.crashes' },
        },
        {
          path: 'applications/:id/monitoring/crashes',
          name: 'applications.monitoring.crashes',
          component: () => import('@/modules/applications/pages/CrashDashboardPage.vue'),
          meta: { title: 'Crash Dashboard', requiresAuth: true },
        },
        {
          path: 'applications/:id/monitoring/health',
          name: 'applications.monitoring.health',
          component: () => import('@/modules/applications/pages/HealthDashboardPage.vue'),
          meta: { title: 'Health Dashboard', requiresAuth: true },
        },
        {
          path: 'applications/:id/monitoring/crashes/:crashId',
          name: 'applications.monitoring.crash',
          component: () => import('@/modules/applications/pages/CrashDetailsPage.vue'),
          meta: { title: 'Crash Details', requiresAuth: true },
        },
        {
          path: 'applications/:id/monitoring/devices',
          name: 'applications.monitoring.devices',
          component: () => import('@/modules/applications/pages/DeviceStatisticsPage.vue'),
          meta: { title: 'Device Statistics', requiresAuth: true },
        },
        {
          path: 'applications/:id/monitoring/charts',
          name: 'applications.monitoring.charts',
          component: () => import('@/modules/applications/pages/MonitoringChartsPage.vue'),
          meta: { title: 'Monitoring Charts', requiresAuth: true },
        },
        {
          path: 'applications/:id/monitoring/alerts',
          name: 'applications.monitoring.alerts',
          component: () => import('@/modules/applications/pages/MonitoringAlertsPage.vue'),
          meta: { title: 'Monitoring Alerts', requiresAuth: true },
        },
        {
          path: 'applications/:id/analytics',
          name: 'applications.analytics',
          component: () => import('@/modules/applications/pages/AnalyticsDashboardPage.vue'),
          meta: { title: 'Analytics Dashboard', requiresAuth: true },
        },
        {
          path: 'applications/:id/analytics/trends',
          name: 'applications.analytics.trends',
          component: () => import('@/modules/applications/pages/AnalyticsTrendsPage.vue'),
          meta: { title: 'Trend Analysis', requiresAuth: true },
        },
        {
          path: 'applications/:id/analytics/heatmap',
          name: 'applications.analytics.heatmap',
          component: () => import('@/modules/applications/pages/AnalyticsHeatmapPage.vue'),
          meta: { title: 'Analytics Heatmap', requiresAuth: true },
        },
        {
          path: 'applications/:id/analytics/countries',
          name: 'applications.analytics.countries',
          component: () => import('@/modules/applications/pages/AnalyticsCountriesPage.vue'),
          meta: { title: 'Country Statistics', requiresAuth: true },
        },
        {
          path: 'applications/:id/analytics/devices',
          name: 'applications.analytics.devices',
          component: () => import('@/modules/applications/pages/AnalyticsDevicesPage.vue'),
          meta: { title: 'Device Statistics', requiresAuth: true },
        },
        {
          path: 'integrations',
          name: 'integrations.index',
          component: () => import('@/modules/integrations/pages/IntegrationsListPage.vue'),
          meta: { title: 'Integrations', requiresAuth: true },
        },
        {
          path: 'integrations/create',
          name: 'integrations.create',
          component: () => import('@/modules/integrations/pages/CreateIntegrationPage.vue'),
          meta: { title: 'Create Integration', requiresAuth: true },
        },
        {
          path: 'integrations/:id',
          name: 'integrations.show',
          component: () => import('@/modules/integrations/pages/IntegrationDetailsPage.vue'),
          meta: { title: 'Integration Details', requiresAuth: true },
        },
        {
          path: 'integrations/:id/edit',
          name: 'integrations.edit',
          component: () => import('@/modules/integrations/pages/EditIntegrationPage.vue'),
          meta: { title: 'Edit Integration', requiresAuth: true },
        },
        {
          path: 'integrations/:id/configuration',
          name: 'integrations.configuration',
          component: () => import('@/modules/integrations/pages/ApiConfigurationPage.vue'),
          meta: { title: 'API Configuration', requiresAuth: true },
        },
        {
          path: 'integrations/:id/connection',
          name: 'integrations.connection',
          component: () => import('@/modules/integrations/pages/ConnectionTestPage.vue'),
          meta: { title: 'Connection Test', requiresAuth: true },
        },
        {
          path: 'integrations/:id/tester',
          name: 'integrations.tester',
          component: () => import('@/modules/integrations/pages/RequestTesterPage.vue'),
          meta: { title: 'Request Tester', requiresAuth: true },
        },
        {
          path: 'integrations/:id/history',
          name: 'integrations.history',
          component: () => import('@/modules/integrations/pages/ConnectionHistoryPage.vue'),
          meta: { title: 'Connection History', requiresAuth: true },
        },
        {
          path: 'webhooks',
          name: 'webhooks.index',
          component: () => import('@/modules/webhooks/pages/WebhooksListPage.vue'),
          meta: { title: 'Webhooks', requiresAuth: true },
        },
        {
          path: 'webhooks/create',
          name: 'webhooks.create',
          component: () => import('@/modules/webhooks/pages/CreateWebhookPage.vue'),
          meta: { title: 'Create Webhook', requiresAuth: true },
        },
        {
          path: 'webhooks/logs',
          name: 'webhooks.logs',
          component: () => import('@/modules/webhooks/pages/WebhookLogsPage.vue'),
          meta: { title: 'Webhook Logs', requiresAuth: true },
        },
        {
          path: 'webhooks/events',
          name: 'webhooks.events',
          component: () => import('@/modules/webhooks/pages/WebhookEventsPage.vue'),
          meta: { title: 'Webhook Events', requiresAuth: true },
        },
        {
          path: 'webhooks/:id',
          name: 'webhooks.show',
          component: () => import('@/modules/webhooks/pages/ViewWebhookPage.vue'),
          meta: { title: 'Webhook Details', requiresAuth: true },
        },
        {
          path: 'webhooks/:id/edit',
          name: 'webhooks.edit',
          component: () => import('@/modules/webhooks/pages/EditWebhookPage.vue'),
          meta: { title: 'Edit Webhook', requiresAuth: true },
        },
        {
          path: 'webhooks/:id/tester',
          name: 'webhooks.tester',
          component: () => import('@/modules/webhooks/pages/WebhookTesterPage.vue'),
          meta: { title: 'Webhook Tester', requiresAuth: true },
        },
        {
          path: 'sync',
          name: 'sync.dashboard',
          component: () => import('@/modules/sync/pages/SyncDashboardPage.vue'),
          meta: { title: 'Sync Dashboard', requiresAuth: true },
        },
        {
          path: 'sync/configs',
          name: 'sync.configs',
          component: () => import('@/modules/sync/pages/SyncConfigsListPage.vue'),
          meta: { title: 'Sync Configs', requiresAuth: true },
        },
        {
          path: 'sync/configs/create',
          name: 'sync.configs.create',
          component: () => import('@/modules/sync/pages/CreateSyncConfigPage.vue'),
          meta: { title: 'Create Sync Config', requiresAuth: true },
        },
        {
          path: 'sync/configs/:id',
          name: 'sync.configs.show',
          component: () => import('@/modules/sync/pages/ViewSyncConfigPage.vue'),
          meta: { title: 'Sync Config', requiresAuth: true },
        },
        {
          path: 'sync/configs/:id/edit',
          name: 'sync.configs.edit',
          component: () => import('@/modules/sync/pages/EditSyncConfigPage.vue'),
          meta: { title: 'Edit Sync Config', requiresAuth: true },
        },
        {
          path: 'sync/history',
          name: 'sync.history',
          component: () => import('@/modules/sync/pages/SyncHistoryPage.vue'),
          meta: { title: 'Sync History', requiresAuth: true },
        },
        {
          path: 'sync/logs',
          name: 'sync.logs',
          component: () => import('@/modules/sync/pages/SyncLogsPage.vue'),
          meta: { title: 'Sync Logs', requiresAuth: true },
        },
        {
          path: 'mappings',
          name: 'mappings.index',
          component: () => import('@/modules/mappings/pages/MappingsListPage.vue'),
          meta: { title: 'Data Mappings', requiresAuth: true },
        },
        {
          path: 'mappings/create',
          name: 'mappings.create',
          component: () => import('@/modules/mappings/pages/CreateMappingPage.vue'),
          meta: { title: 'Create Mapping', requiresAuth: true },
        },
        {
          path: 'mappings/:id',
          name: 'mappings.show',
          component: () => import('@/modules/mappings/pages/ViewMappingPage.vue'),
          meta: { title: 'Mapping Details', requiresAuth: true },
        },
        {
          path: 'mappings/:id/edit',
          name: 'mappings.edit',
          component: () => import('@/modules/mappings/pages/EditMappingPage.vue'),
          meta: { title: 'Edit Mapping', requiresAuth: true },
        },
        {
          path: 'queue',
          name: 'queue.dashboard',
          component: () => import('@/modules/queue/pages/QueueDashboardPage.vue'),
          meta: { title: 'Queue Dashboard', requiresAuth: true },
        },
        {
          path: 'queue/running',
          name: 'queue.running',
          component: () => import('@/modules/queue/pages/QueueRunningPage.vue'),
          meta: { title: 'Running Jobs', requiresAuth: true },
        },
        {
          path: 'queue/failed',
          name: 'queue.failed',
          component: () => import('@/modules/queue/pages/QueueFailedPage.vue'),
          meta: { title: 'Failed Jobs', requiresAuth: true },
        },
        {
          path: 'queue/statistics',
          name: 'queue.statistics',
          component: () => import('@/modules/queue/pages/QueueStatisticsPage.vue'),
          meta: { title: 'Queue Statistics', requiresAuth: true },
        },
        {
          path: 'monitoring',
          name: 'monitoring.dashboard',
          component: () => import('@/modules/monitoring/pages/HealthDashboardPage.vue'),
          meta: { title: 'Health Dashboard', requiresAuth: true },
        },
        {
          path: 'monitoring/realtime',
          name: 'monitoring.realtime',
          component: () => import('@/modules/monitoring/pages/RealtimeStatusPage.vue'),
          meta: { title: 'Real-Time Status', requiresAuth: true },
        },
        {
          path: 'monitoring/api',
          name: 'monitoring.api',
          component: () => import('@/modules/monitoring/pages/ApiMonitorPage.vue'),
          meta: { title: 'API Monitor', requiresAuth: true },
        },
        {
          path: 'monitoring/webhooks',
          name: 'monitoring.webhooks',
          component: () => import('@/modules/monitoring/pages/WebhookMonitorPage.vue'),
          meta: { title: 'Webhook Monitor', requiresAuth: true },
        },
        {
          path: 'monitoring/queue',
          name: 'monitoring.queue',
          component: () => import('@/modules/monitoring/pages/QueueMonitorPage.vue'),
          meta: { title: 'Queue Monitor', requiresAuth: true },
        },
        {
          path: 'monitoring/integrations',
          name: 'monitoring.integrations',
          component: () => import('@/modules/monitoring/pages/IntegrationStatusPage.vue'),
          meta: { title: 'Integration Status', requiresAuth: true },
        },
        {
          path: 'monitoring/timeline',
          name: 'monitoring.timeline',
          component: () => import('@/modules/monitoring/pages/IncidentTimelinePage.vue'),
          meta: { title: 'Incident Timeline', requiresAuth: true },
        },
        {
          path: 'monitoring/history',
          name: 'monitoring.history',
          component: () => import('@/modules/monitoring/pages/ResponseHistoryPage.vue'),
          meta: { title: 'Response History', requiresAuth: true },
        },
        {
          path: 'monitoring/alerts',
          name: 'monitoring.alerts',
          component: () => import('@/modules/monitoring/pages/AlertConfigurationPage.vue'),
          meta: { title: 'Alert Configuration', requiresAuth: true },
        },
        {
          path: 'settings',
          redirect: { name: 'settings.general' },
        },
        {
          path: 'settings/general',
          name: 'settings.general',
          component: () => import('@/modules/settings/pages/GeneralSettingsPage.vue'),
          meta: { title: 'General Settings', requiresAuth: true },
        },
        {
          path: 'settings/email',
          name: 'settings.email',
          component: () => import('@/modules/settings/pages/EmailSettingsPage.vue'),
          meta: { title: 'Email Settings', requiresAuth: true },
        },
        {
          path: 'settings/storage',
          name: 'settings.storage',
          component: () => import('@/modules/settings/pages/StorageSettingsPage.vue'),
          meta: { title: 'Storage Settings', requiresAuth: true },
        },
        {
          path: 'settings/security',
          name: 'settings.security',
          component: () => import('@/modules/settings/pages/SecuritySettingsPage.vue'),
          meta: { title: 'Security Settings', requiresAuth: true },
        },
        {
          path: 'settings/api',
          name: 'settings.api',
          component: () => import('@/modules/settings/pages/ApiSettingsPage.vue'),
          meta: { title: 'API Settings', requiresAuth: true },
        },
        {
          path: 'settings/queue',
          name: 'settings.queue',
          component: () => import('@/modules/settings/pages/QueueSettingsPage.vue'),
          meta: { title: 'Queue Settings', requiresAuth: true },
        },
        {
          path: 'settings/media',
          name: 'settings.media',
          component: () => import('@/modules/settings/pages/MediaLibraryPage.vue'),
          meta: { title: 'Media Library', requiresAuth: true },
        },
        {
          path: 'settings/files',
          name: 'settings.files',
          component: () => import('@/modules/settings/pages/FileManagerPage.vue'),
          meta: { title: 'File Manager', requiresAuth: true },
        },
        {
          path: 'audit',
          redirect: { name: 'audit.activity' },
        },
        {
          path: 'audit/activity',
          name: 'audit.activity',
          component: () => import('@/modules/audit/pages/ActivityLogsPage.vue'),
          meta: { title: 'Activity Logs', requiresAuth: true },
        },
        {
          path: 'audit/trail',
          name: 'audit.trail',
          component: () => import('@/modules/audit/pages/AuditTrailPage.vue'),
          meta: { title: 'Audit Trail', requiresAuth: true },
        },
        {
          path: 'audit/login-history',
          name: 'audit.login',
          component: () => import('@/modules/audit/pages/LoginHistoryPage.vue'),
          meta: { title: 'Login History', requiresAuth: true },
        },
        {
          path: 'audit/system-events',
          name: 'audit.events',
          component: () => import('@/modules/audit/pages/SystemEventsPage.vue'),
          meta: { title: 'System Events', requiresAuth: true },
        },
        {
          path: 'audit/api-logs',
          name: 'audit.api',
          component: () => import('@/modules/audit/pages/ApiLogsPage.vue'),
          meta: { title: 'API Logs', requiresAuth: true },
        },
        {
          path: 'audit/errors',
          name: 'audit.errors',
          component: () => import('@/modules/audit/pages/ErrorLogsPage.vue'),
          meta: { title: 'Error Logs', requiresAuth: true },
        },
        {
          path: 'profile',
          name: 'profile',
          component: () => import('@/modules/users/pages/ProfilePage.vue'),
          meta: { title: 'My Profile', requiresAuth: true },
        },
        {
          path: 'account/change-password',
          name: 'change-password',
          component: () => import('@/modules/authentication/pages/ChangePasswordPage.vue'),
          meta: { title: 'Change Password', requiresAuth: true },
        },
      ],
    },
    {
      path: '/portal',
      component: () => import('@/layouts/PortalLayout.vue'),
      meta: { requiresAuth: true, portal: true },
      children: [
        {
          path: '',
          redirect: { name: 'portal.tickets.index' },
        },
        {
          path: 'tickets',
          name: 'portal.tickets.index',
          component: () => import('@/modules/portal/pages/PortalTicketsPage.vue'),
          meta: { title: 'My Tickets', requiresAuth: true, portal: true },
        },
        {
          path: 'tickets/create',
          name: 'portal.tickets.create',
          component: () => import('@/modules/portal/pages/PortalCreateTicketPage.vue'),
          meta: { title: 'Submit Ticket', requiresAuth: true, portal: true },
        },
        {
          path: 'tickets/:id',
          name: 'portal.tickets.show',
          component: () => import('@/modules/portal/pages/PortalTicketViewPage.vue'),
          meta: { title: 'Ticket Details', requiresAuth: true, portal: true },
        },
      ],
    },
    {
      path: '/:pathMatch(.*)*',
      name: 'not-found',
      component: () => import('@/pages/NotFoundPage.vue'),
      meta: { title: 'Page Not Found' },
    },
  ],
});

router.beforeEach(async (to) => {
  const authStore = useAuthStore();

  if (!authStore.initialized) {
    await authStore.initialize();
  }

  if (to.meta.requiresAuth && !authStore.isAuthenticated) {
    return { name: 'login', query: { redirect: to.fullPath } };
  }

  if (to.meta.guest && authStore.isAuthenticated && to.name !== 'verify-email') {
    return authStore.isPortalCustomer
      ? { name: 'portal.tickets.index' }
      : { name: 'dashboard' };
  }

  if (authStore.isAuthenticated && authStore.isPortalCustomer && !to.meta.portal && to.name !== 'not-found') {
    return { name: 'portal.tickets.index' };
  }

  if (to.meta.portal && authStore.isAuthenticated && !authStore.isPortalCustomer) {
    return { name: 'dashboard' };
  }

  return true;
});

router.afterEach((to) => {
  const baseTitle = import.meta.env.VITE_APP_NAME || 'AMS';
  document.title = to.meta.title ? `${to.meta.title} · ${baseTitle}` : baseTitle;
});

export default router;
